"""initial schema

Revision ID: f4c9da5f1d8b
Revises: 
Create Date: 2026-03-19 00:52:23.866004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core import security


# revision identifiers, used by Alembic.
revision: str = 'f4c9da5f1d8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.Enum('DATE', 'FRIEND', 'COWORKER', 'FAMILY', 'OTHER', name='relationshiptype'), nullable=False),
    sa.Column('is_dating_mode', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('profile_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_data', security.EncryptedJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contacts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('source_platform', sa.Enum('IMESSAGE', 'WHATSAPP', 'TELEGRAM', 'INSTAGRAM', 'ANDROID_SMS', 'CSV', 'SCREENSHOT', 'PASTE', name='importplatform'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_imports_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imports'))
    )
    op.create_index(op.f('ix_imports_contact_id'), 'imports', ['contact_id'], unique=False)
    op.create_table('qa_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_qa_sessions_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_sessions'))
    )
    op.create_index(op.f('ix_qa_sessions_contact_id'), 'qa_sessions', ['contact_id'], unique=False)
    op.create_table('reply_coach_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('incoming_message', sa.Text(), nullable=False),
    sa.Column('subtext_analysis', sa.Text(), nullable=False),
    sa.Column('reply_options', sa.JSON(), nullable=False),
    sa.Column('danger_zones', sa.JSON(), nullable=False),
    sa.Column('timing_recommendation', sa.Text(), nullable=False),
    sa.Column('escalation_guidance', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_reply_coach_sessions_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reply_coach_sessions'))
    )
    op.create_index(op.f('ix_reply_coach_sessions_contact_id'), 'reply_coach_sessions', ['contact_id'], unique=False)
    op.create_table('vault_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_vault_categories_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_categories'))
    )
    op.create_index(op.f('ix_vault_categories_contact_id'), 'vault_categories', ['contact_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'CONTACT', 'SYSTEM', name='sendertype'), nullable=False),
    sa.Column('message_text', security.EncryptedString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'LINK', 'REACTION', 'SYSTEM', name='messagetype'), nullable=False),
    sa.Column('response_time_seconds', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding', security.FlexibleEmbedding(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_messages_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk_messages_import_id_imports'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('contact_id', 'canonical_id', name='uq_messages_contact_canonical_id')
    )
    op.create_index(op.f('ix_messages_canonical_id'), 'messages', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_messages_contact_id'), 'messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_messages_import_id'), 'messages', ['import_id'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('qa_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['qa_sessions.id'], name=op.f('fk_qa_messages_session_id_qa_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_messages'))
    )
    op.create_index(op.f('ix_qa_messages_session_id'), 'qa_messages', ['session_id'], unique=False)
    op.create_table('message_highlights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('highlight_type', sa.Enum('KEY_MOMENT', 'RED_FLAG', 'GREEN_FLAG', 'HUMOR', 'VULNERABILITY', 'CONFLICT', 'MILESTONE', name='highlighttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('profile_section', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_message_highlights_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_highlights_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_highlights'))
    )
    op.create_index(op.f('ix_message_highlights_contact_id'), 'message_highlights', ['contact_id'], unique=False)
    op.create_index(op.f('ix_message_highlights_message_id'), 'message_highlights', ['message_id'], unique=False)
    op.create_table('message_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vault_categories.id'], name=op.f('fk_message_tags_category_id_vault_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_tags_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_tags'))
    )
    op.create_index(op.f('ix_message_tags_category_id'), 'message_tags', ['category_id'], unique=False)
    op.create_index(op.f('ix_message_tags_message_id'), 'message_tags', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_tags_message_id'), table_name='message_tags')
    op.drop_index(op.f('ix_message_tags_category_id'), table_name='message_tags')
    op.drop_table('message_tags')
    op.drop_index(op.f('ix_message_highlights_message_id'), table_name='message_highlights')
    op.drop_index(op.f('ix_message_highlights_contact_id'), table_name='message_highlights')
    op.drop_table('message_highlights')
    op.drop_index(op.f('ix_qa_messages_session_id'), table_name='qa_messages')
    op.drop_table('qa_messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_import_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_contact_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_canonical_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_vault_categories_contact_id'), table_name='vault_categories')
    op.drop_table('vault_categories')
    op.drop_index(op.f('ix_reply_coach_sessions_contact_id'), table_name='reply_coach_sessions')
    op.drop_table('reply_coach_sessions')
    op.drop_index(op.f('ix_qa_sessions_contact_id'), table_name='qa_sessions')
    op.drop_table('qa_sessions')
    op.drop_index(op.f('ix_imports_contact_id'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
